const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={libraries:JSON.parse(localStorage.getItem('jweds-libraries')||'null')||[
{name:"Robbo's Trakway Trivia",type:'Generated',voice:'Robbo (Gemini)',phrases:94,status:'Ready'},
{name:'Site Induction Pack',type:'Generated',voice:'Joe (Clone)',phrases:38,status:'Ready'}],settings:JSON.parse(localStorage.getItem('jweds-settings')||'{}')};
function show(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0)}
$$('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>show(b.dataset.jump));
function renderLibraries(){let rows=state.libraries.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.type}</td><td>${x.voice}</td><td>${x.phrases}</td><td><span class="badge">● ${x.status}</span></td></tr>`).join('');let html=`<table class="table"><thead><tr><th>Name</th><th>Type</th><th>Voice</th><th>Phrases</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table>`;$('#recentTable').innerHTML=html;$('#libraryList').innerHTML=html} renderLibraries();
$('#loadRobbo').onclick=async()=>{const d=await fetch('robbos-trakway-trivia.json').then(r=>r.json());$('#libraryName').value="Robbo's Trakway Trivia";$('#gender').value='Male';$('#age').value='40s';$('#accent').value='Chesterfield / Mansfield / Worksop, East Midlands';$('#mood').value='Energetic game-show host, dry site banter, warm, confident, mischievous';$('#description').value=`Use the bundled Robbo's Trakway Trivia phrase library (${Array.isArray(d)?d.length:(d.phrases?.length||94)} phrases). Keep each phrase as an individual audio asset.`};
$('#robboTile').onclick=()=>{show('create');$('#loadRobbo').click()};
$('#createForm').onsubmit=e=>{e.preventDefault();const desc=$('#description').value.trim();const count=Math.max(1,(desc.match(/\n/g)||[]).length+1);$('#planOutput').classList.remove('hidden');$('#planOutput').innerHTML=`<h2>Phrase plan ready</h2><p><b>${$('#libraryName').value}</b></p><p>Voice: ${$('#gender').value}, ${$('#age').value}, ${$('#accent').value||'accent not specified'}; ${$('#mood').value||'neutral delivery'}.</p><p>The next stage is an audition before batch rendering. In Local mode this is sent to the JW EDS local voice server.</p><button class="primary" id="goClone">Continue to voice source</button>`;$('#goClone').onclick=()=>show($('#voiceSource').value==='clone'?'clone':'designer')};
let mediaRecorder,chunks=[],startInt,startT;
$('#recordBtn').onclick=async()=>{if(mediaRecorder?.state==='recording'){mediaRecorder.stop();return}if(!$('#consent').checked){alert('Confirm permission to clone the voice first.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>chunks.push(e.data);mediaRecorder.onstop=()=>{clearInterval(startInt);stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:mediaRecorder.mimeType||'audio/webm'});const url=URL.createObjectURL(blob);$('#refAudio').src=url;$('#refAudio').hidden=false;$('#sampleInfo').textContent=`Recorded sample • ${(blob.size/1024).toFixed(0)} KB • ready to save`;$('#recordBtn').textContent='● Record again'};mediaRecorder.start();startT=Date.now();$('#recordBtn').textContent='■ Stop recording';startInt=setInterval(()=>{let s=Math.floor((Date.now()-startT)/1000);$('#timer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`},250)}catch(err){alert('Microphone access was not available: '+err.message)}};
$('#audioFile').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#refAudio').src=URL.createObjectURL(f);$('#refAudio').hidden=false;$('#sampleInfo').textContent=`${f.name} • ${(f.size/1024/1024).toFixed(2)} MB • ready to save`};
$('#saveProfile').onclick=()=>{if(!$('#consent').checked)return alert('Confirm permission first.');const n=$('#profileName').value.trim()||'Unnamed voice';localStorage.setItem('jweds-last-profile',n);$('#sampleInfo').textContent=`Voice profile “${n}” saved locally in this PWA. Connect the local engine to synthesize cloned speech.`};
$('#checkLocal').onclick=async()=>{let u=$('#localUrl')?.value||state.settings.localUrl||'http://127.0.0.1:8765';try{let r=await fetch(u.replace(/\/$/,'')+'/health',{signal:AbortSignal.timeout(2500)});if(!r.ok)throw Error(r.status);$('.dot').classList.add('ok');$('#localStatus').textContent='Connected'}catch(e){$('.dot').classList.remove('ok');$('#localStatus').textContent='Not connected'}};
$('#saveSettings').onclick=()=>{state.settings={mode:$('#mode').value,localUrl:$('#localUrl').value};localStorage.setItem('jweds-settings',JSON.stringify(state.settings));alert('Settings saved on this device.')};
if(state.settings.mode)$('#mode').value=state.settings.mode;if(state.settings.localUrl)$('#localUrl').value=state.settings.localUrl;
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}else alert('In Safari use Share → Add to Home Screen.')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
